sudo: required
language: go
go:
  - 1.11.x
  - 1.12.x
  - master
go_import_path: github.com/ClickHouse-Ninja/ok
services:
  - docker
before_install:
  - docker --version
  - go get -t -v ./...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
